### PR TITLE
Added Swedish translation

### PR DESCRIPTION
**Pull request by IAmLythixIAmDumb**

### CODE REVIEW

**Comment by samerton** [comment]
Thanks for this! Could the folder be renamed to `SwedishSE` so it matches the [Nameless translation](https://github.com/NamelessMC/Nameless/tree/v2/custom/languages/SwedishSE)?

**Comment by IAmLythixIAmDumb** [comment]
> Thanks for this! Could the folder be renamed to `SwedishSE` so it matches the [Nameless translation](https://github.com/NamelessMC/Nameless/tree/v2/custom/languages/SwedishSE)?

Sure thing!

**Comment by IAmLythixIAmDumb** [comment]
Should be good to go.

**Comment by samerton** [comment]
Thanks again

**Comment by IAmLythixIAmDumb** [comment]
Happy to help out!

**Pull request merged**
